src/objects/PURGER_TIME_EXPIRATION__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>EXPIRATION_TIME__c</fullName>
        <label>EXPIRATION_TIME</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>PURGER TIME EXPIRATION</label>
</CustomObject>

src/objects/Tracking_LOG__c.object
<CustomObject>
    <fields>
        <fullName>END_CPUTIME__c</fullName>
        <label>CPUTIME</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>END_DATE__c</fullName>
        <label>END DATE</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>END_DML_OPERATIONS__c</fullName>
        <label>DML OPERATIONS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>END_HEAPSIZE__c</fullName>
        <label>HEAPSIZE</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>END_QUERYS__c</fullName>
        <label>QUERYS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ERROR_DESCRIPTION__c</fullName>
        <label>ERROR DESCRIPTION</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERROR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ERROR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EXCEPTION__c</fullName>
        <label>EXCEPTION</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LINE_NUMBER__c</fullName>
        <label>LINE NUMBER</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>QUANTITY_RECORDS__c</fullName>
        <label>QUANTITY RECORDS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>REQUEST__c</fullName>
        <label>REQUEST</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RESPONSE__c</fullName>
        <label>RESPONSE</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>STACKTRACE__c</fullName>
        <label>STACKTRACE</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>START_CPUTIME__c</fullName>
        <label>CPUTIME</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>START_DATE__c</fullName>
        <label>START DATE</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>START_DML_OPERATIONS__c</fullName>
        <label>DML OPERATIONS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>START_HEAPSIZE__c</fullName>
        <label>HEAPSIZE</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>START_QUERYROWS__c</fullName>
        <label>QUERYROWS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TYPE__c</fullName>
        <label>TYPE</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Batch</fullName>
                </value>
                <value>
                    <fullName>Future</fullName>
                </value>
                <value>
                    <fullName>Lightning Component</fullName>
                </value>
                <value>
                    <fullName>Lightning web</fullName>
                </value>
                <value>
                    <fullName>Scheduler</fullName>
                </value>
                <value>
                    <fullName>Trigger</fullName>
                </value>
                <value>
                    <fullName>Visualforce</fullName>
                </value>
                <value>
                    <fullName>Webservice</fullName>
                </value>
                <value>
                    <fullName>Common</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VERSION__c</fullName>
        <label>VERSION</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Tracking LOG</label>
    <nameField>
        <label>Tracking LOG Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tracking LOGS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRACKING_LOG_HISTORIC__b.object
<CustomObject>
    <fields>
        <fullName>END_CPUTIME__c</fullName>
        <label>END CPUTIME</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>END_DATE__c</fullName>
        <label>END DATE</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>END_DML_OPERATIONS__c</fullName>
        <label>END DML OPERATIONS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>END_HEAPSIZE__c</fullName>
        <label>END HEAPSIZE</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>END_QUERYS__c</fullName>
        <label>END QUERY</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ERROR_DESCRIPTION__c</fullName>
        <label>ERROR DESCRIPTION</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERROR__c</fullName>
        <label>ERROR</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EXCEPTION__c</fullName>
        <label>EXCEPTION</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LINE_NUMBER__c</fullName>
        <label>LINE NUMBER</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>QUANTITY_RECORDS__c</fullName>
        <label>QUANTITY RECORDS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>REQUEST__c</fullName>
        <label>REQUEST</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RESPONSE__c</fullName>
        <label>RESPONSE</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>STACKTRACE__c</fullName>
        <label>STACKTRACE</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>START_CPUTIME__c</fullName>
        <label>START CPUTIME</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>START_DATE__c</fullName>
        <label>START DATE</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>START_DML_OPERATIONS__c</fullName>
        <label>START DML OPERATIONS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>START_HEAPSIZE__c</fullName>
        <label>START HEAPSIZE</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>START_QUERYROWS__c</fullName>
        <label>START QUERYROWS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TYPE__c</fullName>
        <label>TYPE</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VERSION__c</fullName>
        <label>VERSION</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Tracking Log historic</label>
    <pluralLabel>Tracking Logs historic</pluralLabel>
</CustomObject>

src/classes/PurgerTrackLogFactory.cls
global class PurgerTrackLogFactory{

  private list<Tracking_LOG__c> trackingLog;
  private list<Tracking_LOG_Historic__b> lsttrackoHistoric = new list<Tracking_LOG_Historic__b>();
  private Integer ExpirationTime;

  global PurgerTrackLogFactory(list<Tracking_LOG__c> trackingLog){
    this.trackingLog = trackingLog;
  } 

  public list<Tracking_LOG_Historic__b> getlistTrackHistoric(){
      return this.lsttrackoHistoric;
  }

  public Integer getExpirationTime(){
    PURGER_TIME_EXPIRATION__c prg = PURGER_TIME_EXPIRATION__c.getValues('purger');
    this.ExpirationTime = Integer.valueOf(prg.Expiration_Time__c);
    return this.ExpirationTime;
  }

  public void createHistoric(){

    for(Tracking_LOG__c tck: this.trackingLog){

       Tracking_LOG_Historic__b trackingHistoric = new Tracking_LOG_Historic__b();

       trackingHistoric.END_CPUTIME__c = tck.END_CPUTIME__c;
       trackingHistoric.END_DATE__c = tck.END_DATE__c;
       trackingHistoric.END_DML_OPERATIONS__c = tck.END_DML_OPERATIONS__c;
       trackingHistoric.END_HEAPSIZE__c = tck.END_HEAPSIZE__c;
       trackingHistoric.END_QUERYS__c = tck.END_QUERYS__c;
       trackingHistoric.ERROR_DESCRIPTION__c = tck.ERROR_DESCRIPTION__c;
       trackingHistoric.ERROR__c = String.valueof(tck.ERROR__c);
       trackingHistoric.EXCEPTION__c = tck.EXCEPTION__c;
       trackingHistoric.LINE_NUMBER__c = tck.LINE_NUMBER__c;
       trackingHistoric.QUANTITY_RECORDS__c = tck.QUANTITY_RECORDS__c;
       trackingHistoric.REQUEST__c = tck.REQUEST__c;
       trackingHistoric.RESPONSE__c = tck.RESPONSE__c;
       trackingHistoric.STACKTRACE__c = tck.STACKTRACE__c;
       trackingHistoric.START_CPUTIME__c = tck.START_CPUTIME__c;
       trackingHistoric.START_DATE__c = tck.START_DATE__c;
       trackingHistoric.START_DML_OPERATIONS__c = tck.START_DML_OPERATIONS__c;
       trackingHistoric.START_HEAPSIZE__c = tck.START_HEAPSIZE__c;
       trackingHistoric.START_QUERYROWS__c = tck.START_QUERYROWS__c;
       trackingHistoric.TYPE__c = tck.TYPE__c;
       trackingHistoric.VERSION__c = tck.VERSION__c;

       this.lsttrackoHistoric.add(trackingHistoric);
    }
  }



}