src/objects/TRACKING_LOG_EVENT__e.object
<CustomObject>
    <fields>
        <fullName>END_CPUTIME__c</fullName>
        <label>END_CPUTIME</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>END_DATE__c</fullName>
        <label>END_DATE</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>END_DML_OPERATIONS__c</fullName>
        <label>END_DML_OPERATIONS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>END_HEAPSIZE__c</fullName>
        <label>END_HEAPSIZE</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>END_QUERYROWS__c</fullName>
        <label>END_QUERYROWS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>END_QUERYS__c</fullName>
        <label>END_QUERYS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ERROR_DESCRIPTION__c</fullName>
        <label>ERROR_DESCRIPTION</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERROR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ERROR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EXCEPTION__c</fullName>
        <label>EXCEPTION</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KEY__c</fullName>
        <label>KEY</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LINE_NUMBER__c</fullName>
        <label>LINE_NUMBER</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NAME__c</fullName>
        <label>NAME</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QUANTITY_RECORDS__c</fullName>
        <label>QUANTITY_RECORDS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>REQUEST__c</fullName>
        <label>REQUEST</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>STACKTRACE__c</fullName>
        <label>STACKTRACE</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>START_CPUTIME__c</fullName>
        <label>START_CPUTIME</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>START_DATE__c</fullName>
        <label>START_DATE</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>START_DML_OPERATIONS__c</fullName>
        <label>START_DML_OPERATIONS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>START_HEAPSIZE__c</fullName>
        <label>START_HEAPSIZE</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>START_QUERYROWS__c</fullName>
        <label>START_QUERYROWS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>START_QUERYS__c</fullName>
        <label>START_QUERYS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>STATUS__c</fullName>
        <label>STATUS</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>TRACKING LOG EVENT</label>
    <pluralLabel>TRACKING LOG EVENTS</pluralLabel>
</CustomObject>

src/classes/ILoggerFactory.cls
global class ILoggerFactory{
 
  private TRACKING_LOG_EVENT__e log = new TRACKING_LOG_EVENT__e();

  global ILoggerFactory(TRACKING_LOG_EVENT__e aLog){
    this.log = aLog;
  }

  global TRACKING_LOG_EVENT__e getLog(){
    return this.log;
  }

  global String getLogName(){
    return this.log.NAME__c;
  }

  global void setRequest(Blob req){
     this.log.Request__c = ILogUtil.ConvertTypetoString(req);
  }
  
  global void setRequest(Object req){
     this.log.Request__c = ILogUtil.ConvertTypetoString(req);
  }

  global void startLog(ILoggerRequest req){

    this.log.START_CPUTIME__c = limits.getCpuTime();
    this.log.START_QUERYROWS__c = limits.getQueryRows();
    this.log.START_HEAPSIZE__c = limits.getHeapSize();
    this.log.START_DML_OPERATIONS__c = limits.getDMLStatements();
    this.log.QUANTITY_RECORDS__c = limits.getDmlrows();
    this.log.START_QUERYS__c = limits.getQueries();
    this.log.NAME__c = req.getClassName();
    this.log.START_DATE__c = system.now();
    this.log.STATUS__c = 'Pending';
    this.log.KEY__c = this.generateKey();
  }
 
  global TRACKING_LOG_EVENT__e endLog(){
    this.log.END_CPUTIME__c = limits.getCpuTime();
    this.log.END_QUERYROWS__c = limits.getQueryRows();
    this.log.END_HEAPSIZE__c = limits.getHeapSize();
    this.log.END_QUERYS__c = limits.getQueries();
    this.log.END_DML_OPERATIONS__c = limits.getDMLStatements();
    this.log.END_DATE__c = system.now();
    this.log.STATUS__c = 'Finished';
    return this.log;
  }

  global TRACKING_LOG_EVENT__e setException(Exception ex){
    this.log.EXCEPTION__c = ex.getTypeName();
    this.log.ERROR__c = true;
    this.log.LINE_NUMBER__c = ex.getLineNumber();
    this.log.ERROR_DESCRIPTION__c = ex.getMessage();  
    this.log.STACKTRACE__c = ex.getStackTraceString();

    return this.log;
   }

   private String generateKey(){
      String senhaGerada;
      Blob blobKey = crypto.generateAesKey(128);
      String key = EncodingUtil.convertToHex(blobKey);
      senhaGerada = key.substring(0,15);
      
      return senhaGerada;
   }
}