src/objects/TRACKING_LOG_EVENT__e.object
<CustomObject>
    <fields>
        <fullName>START_DATE__c</fullName>
        <label>START_DATE</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>TYPE__c</fullName>
        <label>TYPE</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VERSION__c</fullName>
        <label>VERSION</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>TRACKING LOG EVENT</label>
    <pluralLabel>TRACKING LOG EVENTS</pluralLabel>
</CustomObject>

src/classes/ILoggerResponse.cls
global class ILoggerResponse {
   
   private TRACKING_LOG_EVENT__e log = new TRACKING_LOG_EVENT__e();
   private ILoggerException exct = new ILoggerException();
   private final String pckVersion = '1.0';

   global ILoggerResponse(){
     this.log.START_DATE__c = system.now();
     this.log.TYPE__c = ILogUtil.getExecutionType(); 
     this.log.VERSION__c = pckVersion;    
   }

   global TRACKING_LOG_EVENT__e getTrackRsp(){
      return this.log;
   }
}