src/objects/Tracking_LOG__c.object
<CustomObject>
    <fields>
        <fullName>END_CPUTIME__c</fullName>
        <label>CPUTIME</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>END_DATE__c</fullName>
        <label>END DATE</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>END_DML_OPERATIONS__c</fullName>
        <label>DML OPERATIONS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>END_HEAPSIZE__c</fullName>
        <label>HEAPSIZE</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>END_QUERYROWS__c</fullName>
        <label>QUERYROWS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>END_QUERYS__c</fullName>
        <label>QUERYS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ERROR_DESCRIPTION__c</fullName>
        <label>ERROR DESCRIPTION</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERROR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ERROR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EXCEPTION__c</fullName>
        <label>EXCEPTION</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KEY__c</fullName>
        <externalId>true</externalId>
        <label>KEY</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LINE_NUMBER__c</fullName>
        <label>LINE NUMBER</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>QUANTITY_RECORDS__c</fullName>
        <label>QUANTITY RECORDS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>REQUEST__c</fullName>
        <label>REQUEST</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RESPONSE__c</fullName>
        <label>RESPONSE</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>STACKTRACE__c</fullName>
        <label>STACKTRACE</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>START_CPUTIME__c</fullName>
        <label>CPUTIME</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>START_DATE__c</fullName>
        <label>START DATE</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>START_DML_OPERATIONS__c</fullName>
        <label>DML OPERATIONS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>START_HEAPSIZE__c</fullName>
        <label>HEAPSIZE</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>START_QUERYROWS__c</fullName>
        <label>QUERYROWS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>STATUS__c</fullName>
        <label>STATUS</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Finished</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TYPE__c</fullName>
        <label>TYPE</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Batch</fullName>
                </value>
                <value>
                    <fullName>Future</fullName>
                </value>
                <value>
                    <fullName>Lightning Component</fullName>
                </value>
                <value>
                    <fullName>Lightning web</fullName>
                </value>
                <value>
                    <fullName>Scheduler</fullName>
                </value>
                <value>
                    <fullName>Trigger</fullName>
                </value>
                <value>
                    <fullName>Visualforce</fullName>
                </value>
                <value>
                    <fullName>Webservice</fullName>
                </value>
                <value>
                    <fullName>Common</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tracking LOG</label>
    <nameField>
        <label>Tracking LOG Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tracking LOGS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TRACKING_LOG_EVENT__e.object
<CustomObject>
    <fields>
        <fullName>END_CPUTIME__c</fullName>
        <label>END_CPUTIME</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>END_DATE__c</fullName>
        <label>END_DATE</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>END_DML_OPERATIONS__c</fullName>
        <label>END_DML_OPERATIONS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>END_HEAPSIZE__c</fullName>
        <label>END_HEAPSIZE</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>END_QUERYROWS__c</fullName>
        <label>END_QUERYROWS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>END_QUERYS__c</fullName>
        <label>END_QUERYS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ERROR_DESCRIPTION__c</fullName>
        <label>ERROR_DESCRIPTION</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ERROR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ERROR</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>EXCEPTION__c</fullName>
        <label>EXCEPTION</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>KEY__c</fullName>
        <label>KEY</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LINE_NUMBER__c</fullName>
        <label>LINE_NUMBER</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>NAME__c</fullName>
        <label>NAME</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QUANTITY_RECORDS__c</fullName>
        <label>QUANTITY_RECORDS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>REQUEST__c</fullName>
        <label>REQUEST</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>RESPONSE__c</fullName>
        <label>RESPONSE</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>STACKTRACE__c</fullName>
        <label>STACKTRACE</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>START_CPUTIME__c</fullName>
        <label>START_CPUTIME</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>START_DATE__c</fullName>
        <label>START_DATE</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>START_DML_OPERATIONS__c</fullName>
        <label>START_DML_OPERATIONS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>START_HEAPSIZE__c</fullName>
        <label>START_HEAPSIZE</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>START_QUERYROWS__c</fullName>
        <label>START_QUERYROWS</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>STATUS__c</fullName>
        <label>STATUS</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TYPE__c</fullName>
        <label>TYPE</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>TRACKING LOG EVENT</label>
    <pluralLabel>TRACKING LOG EVENTS</pluralLabel>
</CustomObject>

src/classes/TrackingLogEventHandler.cls
global class TrackingLogEventHandler{
  

  private list<TRACKING_LOG_EVENT__e> lstEvent = new list<TRACKING_LOG_EVENT__e>();
  private map<String, Tracking_LOG__c> mapTrack = new map<String, Tracking_LOG__c>();

  private IRepositoryFactory repositoryFactory;
  
  global TrackingLogEventHandler(IRepositoryFactory repositoryFactory){
      this.repositoryFactory = repositoryFactory;
  }

  public TrackingLogEventHandler(list<TRACKING_LOG_EVENT__e> aListEvent){
     this(new RepositoryFactory());
     this.lstEvent = aListEvent;
  }

  public void execute(){

    map<String, Tracking_LOG__c> mapTracklog = new map<String, Tracking_LOG__c>();
    this.getTracks();
    Tracking_LOG__c  tck;

    for(TRACKING_LOG_EVENT__e evt: this.lstEvent){
      system.debug('evt = ' + evt);
      tck = this.mapTrack.get(evt.KEY__c);

      if(tck == null) tck = mapTracklog.get(evt.KEY__c);
      if(tck == null) tck = new Tracking_LOG__c();

      if(checkIsNullorBlank(tck.START_CPUTIME__c)) tck.START_CPUTIME__c = evt.START_CPUTIME__c;
      if(checkIsNullorBlank(tck.END_CPUTIME__c)) tck.END_CPUTIME__c = evt.END_CPUTIME__c;
      if(checkIsNullorBlank(tck.START_DML_OPERATIONS__c)) tck.START_DML_OPERATIONS__c = evt.START_DML_OPERATIONS__c;
      if(checkIsNullorBlank(tck.END_DML_OPERATIONS__c)) tck.END_DML_OPERATIONS__c = evt.END_DML_OPERATIONS__c;
      if(checkIsNullorBlank(tck.END_DATE__c)) tck.END_DATE__c = evt.END_DATE__c;
      if(!tck.ERROR__c) tck.ERROR__c = evt.ERROR__c;
      if(checkIsNullorBlank(tck.ERROR_DESCRIPTION__c)) tck.ERROR_DESCRIPTION__c = evt.ERROR_DESCRIPTION__c;
      if(checkIsNullorBlank(tck.EXCEPTION__c)) tck.EXCEPTION__c = evt.EXCEPTION__c;
      if(checkIsNullorBlank(tck.START_HEAPSIZE__c)) tck.START_HEAPSIZE__c = evt.START_HEAPSIZE__c;
      if(checkIsNullorBlank(tck.END_HEAPSIZE__c)) tck.END_HEAPSIZE__c = evt.END_HEAPSIZE__c;
      if(checkIsNullorBlank(tck.LINE_NUMBER__c)) tck.LINE_NUMBER__c = evt.LINE_NUMBER__c;
      if(checkIsNullorBlank(tck.QUANTITY_RECORDS__c))tck.QUANTITY_RECORDS__c = evt.QUANTITY_RECORDS__c;
      if(checkIsNullorBlank(tck.START_QUERYROWS__c)) tck.START_QUERYROWS__c = evt.START_QUERYROWS__c;
      if(checkIsNullorBlank(tck.END_QUERYROWS__c)) tck.END_QUERYROWS__c = evt.END_QUERYROWS__c;
      if(checkIsNullorBlank(tck.END_QUERYS__c)) tck.END_QUERYS__c = evt.END_QUERYS__c;
      if(checkIsNullorBlank(tck.REQUEST__c)) tck.REQUEST__c = evt.REQUEST__c;
      if(checkIsNullorBlank(tck.RESPONSE__c)) tck.RESPONSE__c = evt.RESPONSE__c;
      if(checkIsNullorBlank(tck.STACKTRACE__c)) tck.STACKTRACE__c = evt.STACKTRACE__c;
      if(checkIsNullorBlank(tck.START_DATE__c)) tck.START_DATE__c = evt.START_DATE__c;
      tck.STATUS__c = evt.STATUS__c;
      if(checkIsNullorBlank(tck.TYPE__c)) tck.TYPE__c = evt.TYPE__c;
      if(checkIsNullorBlank(tck.KEY__c)) tck.KEY__c = evt.KEY__c;
      if(checkIsNullorBlank(tck.Name)) tck.Name = evt.Name__c;

      mapTracklog.put(tck.KEY__c, tck);
    }
      system.debug('mapTracklog = ' + mapTracklog);

    Database.upsert(mapTracklog.values(), Tracking_LOG__c.KEY__c);
  } 

  private void getTracks(){ 

    list<Tracking_LOG__c> lsttrack = new list<Tracking_LOG__c>();
    list<String> lstKeys = new list<String>();

    for(TRACKING_LOG_EVENT__e tcke: this.lstEvent){
        lstKeys.add(tcke.Key__c);
    }

    IRepository repository = RepositoryFactory.create(Tracking_LOG__c.SobjectType);
    Specification spec = new TrackingLogEventSpec(lstKeys);
    Repository.QueryBuilder queryBuilder = new Repository.QueryBuilder()
    .selectFields(FieldSetUtil.getFieldsFromFieldSet(Tracking_LOG__c.SObjectType, 'PURGERFIELDS'))
    .whereSpecification(spec);
    lsttrack = repository.queryObjects(queryBuilder);
    
    for(Tracking_LOG__c tck: lsttrack){
      this.mapTrack.put(tck.key__c, tck);
    }

    lstKeys.clear();
    lsttrack.clear();
  }  

  private Boolean checkIsNullorBlank(Decimal aVlr){
    return (aVlr == null);
  }

  private Boolean checkIsNullorBlank(String aVlr){
    return (String.isBlank(aVlr));
  }

  private Boolean checkIsNullorBlank(Datetime aVlr){
    return (aVlr == null);
  }

}