src/objects/Tracking_LOG__c.object
<CustomObject>
    <fields>
        <fullName>STATUS__c</fullName>
        <label>STATUS</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Finished</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Tracking LOG</label>
    <nameField>
        <label>Tracking LOG Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tracking LOGS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TrackingLogAsyncStatusSchTest.cls
@isTest
private class TrackingLogAsyncStatusSchTest {
    
    @testSetup
    static void setup(){
        
      Tracking_LOG__c tck = new Tracking_LOG__c();
      tck.STATUS__c = 'Pending';

      Database.insert(tck);        
    }
    
    testMethod static void rodo_rotina_que_muda_status_dos_registros(){
        
        test.startTest();
          system.schedule('TrackingLoggerSch', '0 0 0 * * ? *', new TrackingLogAsyncStatusSch());
        test.stopTest();
    }

}