src/objects/Tracking_log_setting__mdt.object
<CustomObject>
    <fields>
        <fullName>REGISTER_ERROR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Register Error</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>REGISTER_SUCCESS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Register Success</label>
        <type>Checkbox</type>
    </fields>
    <label>Tracking log setting</label>
    <pluralLabel>Tracking log settings</pluralLabel>
</CustomObject>

src/classes/ILoggerHelper.cls
global class ILoggerHelper{

  list<Tracking_log_setting__mdt> lstLogSetting;

  global ILoggerHelper(String ClassName){
    this.lstLogSetting = [SELECT Register_Error__c, Register_Success__c 
                          FROM Tracking_log_setting__mdt WHERE DeveloperName =: ClassName];
  }

  global boolean shouldIGenerateError(){
    return (test.isRunningTest()) ? true : this.lstLogSetting[0].Register_Error__c;
  }

  global boolean shouldIGenerateSuccess(){
    return (test.isRunningTest()) ? true : this.lstLogSetting[0].Register_Success__c;
  }
    
}