src/objects/Tracking_LOG__c.object
<CustomObject>
    <fields>
        <fullName>KEY__c</fullName>
        <externalId>true</externalId>
        <label>KEY</label>
        <length>18</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Tracking LOG</label>
    <nameField>
        <label>Tracking LOG Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tracking LOGS</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TrackingLogEventSpec.cls
global class TrackingLogEventSpec extends CompositeSpecification{

    private list<String> lstKeys = new list<String>();

    global TrackingLogEventSpec(list<String> aLstKeys){
        for(String key: aLstKeys)
          this.lstKeys.add('\''+key+'\'');
    }
    
    global override Boolean isSatisfiedBy(Object obj) {
 		return (obj instanceof Tracking_LOG__c);
    }

    global override String toSOQLClauses() {
        return 'Key__c IN ' + this.lstKeys;
    }
}